### PR TITLE
fixes #169 - consistent markers loading

### LINKED ISSUE #169: Markers loading late in iOS
Currently, the markers are working fine on Android. On iOS, sometimes the default markers are shown.

### Reproduction steps
1. Launch app on iOS
1. Go to a campus using the swap button

### PR DESCRIPTION
**Pull request by a-drew**
## Description

Moved the icon loading code from building data back down to the building. The building class should be aware of not only its attributes aka path to logo but also responsible for retrieving and loading the icon bitmap. 

## Related Issues

#169

### CODE REVIEW

File: lib/providers/buildings_data.dart [hunk 1]
```diff
@@ -1,16 +1,13 @@
...
 import 'package:google_maps_flutter/google_maps_flutter.dart';
+import 'package:flutter/material.dart';
 import 'package:flutter/widgets.dart';
-import 'dart:ui' as ui;
 
 ///Observer Pattern
 ///Handles data related to campus buildings, listens to changes and notifies listeners.
 class BuildingsData extends ChangeNotifier {
-  static List<Building> allBuildings = [];
+  List<Building> allBuildings = [];
```
Comment (andrelegault) [inline lib/providers/buildings_data.dart:10]: This is going to change how we load floors for indoor navigation. I'll check if this change doesn't break anything that can't be fixed.

File: lib/providers/buildings_data.dart [hunk 2]
```diff
@@ -25,15 +22,13 @@ class BuildingsData extends ChangeNotifier {
 
   BuildingsData() {
     // Make one big set of buildings that has sgw + loy buildings
-    allBuildings = Search.supported.whereType<Building>().toList();
+    University.concordia.children.forEach((campus) {
+      allBuildings.addAll(campus.children.whereType<Building>());
+    });
```
Comment (andrelegault) [inline lib/providers/buildings_data.dart:27]: This implies that the provider can't be lazy loaded, since we load assets during the splash screen. If it is lazy loaded it would be instantiated before the splash screen is created resulting in there being no data.

**Review by andrelegault — APPROVED** [review]
